Develop
mosip/id-repository pull request #1075
Opened 2024-08-27 13:31 UTC by Sohandey

2024-09-02 07:46 UTC, mohanachandran-s requested changes

2024-09-02 07:46 UTC, mohanachandran-s commented on apitest/src/main/resources/idRepository/UpdateIdentityArrayHandle/UpdateIdentityArrayHandle.yml
Check the indentation for few input parameters in all test cases of this file

2024-09-11 06:39 UTC, lsivanand approved these changes

2024-09-19 03:58 UTC, mohanachandran-s approved these changes

2024-09-20 10:27 UTC, merged