[MOSIP-13847] deprecated biometricReferenceId
mosip/id-repository pull request #275
Opened 2021-05-28 11:31 UTC by manojsp12

2021-05-28 11:40 UTC, LoganathanSekar7627 requested changes

2021-05-28 11:40 UTC, LoganathanSekar7627 commented on id-repository/pom.xml
> +<!-- 		<module>id-repository-vid-service</module> -->
Please uncomment the vid service

2021-05-28 11:47 UTC, manojsp12 commented on id-repository/pom.xml
> +<!-- 		<module>id-repository-vid-service</module> -->
there is no changes in vid service Loga

2021-05-28 11:52 UTC, LoganathanSekar7627 approved these changes

2021-05-28 11:52 UTC, LoganathanSekar7627 commented
Approved

2021-05-31 12:11 UTC, gsasikumar requested changes

2021-05-31 12:11 UTC, gsasikumar commented on id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/RequestDTO.java
> +	@Deprecated(since = "1.1.4")
it should be since 1.1.4.3

2021-05-31 12:57 UTC, manojsp12 commented on id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/RequestDTO.java
> +	@Deprecated(since = "1.1.4")
Updated to 1.1.4.3

2021-05-31 13:16 UTC, gsasikumar approved these changes

2021-05-31 13:16 UTC, merged