INJI-163
mosip/id-repository pull request #804
Opened 2023-07-20 10:56 UTC by dhanendra06

2023-07-20 15:03 UTC, dhanendra06 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +					}else if((key.getFormat() != null)
it will come mono for your policy you will not define for bestTwoFinger as format

2023-07-20 15:04 UTC, dhanendra06 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +						convertRequestDto.setVersion("ISO19794_5_2011");
okay

2023-07-20 15:14 UTC, dhanendra06 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +		return new byte[0];
taken care

2023-07-24 09:33 UTC, LoganathanSekar7627 requested changes

2023-07-24 09:33 UTC, LoganathanSekar7627 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +	private String convertRequestVer;
This is not used. Can we remove this?

2023-07-24 09:33 UTC, LoganathanSekar7627 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +					}else if((key.getFormat() != null)
Please resolve this comment.

2023-07-24 09:41 UTC, dhanendra06 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +	private String convertRequestVer;
taken care

2023-07-24 09:41 UTC, dhanendra06 commented on id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/CredentialProvider.java
> +					}else if((key.getFormat() != null)
this is not required

2023-07-24 09:46 UTC, LoganathanSekar7627 approved these changes

2023-07-24 09:47 UTC, merged