Mosip 29500 1 1 5 5 optimize object store rest calls in idrepo identity service while getting the raw biometric file
mosip/id-repository pull request #828
Opened 2023-09-27 11:53 UTC by Neha2365

2023-09-27 12:08 UTC, vishwa-vyom requested changes

2023-09-27 14:26 UTC, Neha2365 commented on id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/ObjectStoreHelper.java
> +			throw new IdRepoAppUncheckedException(FILE_NOT_FOUND);
Changes done

2023-09-27 14:33 UTC, vishwa-vyom commented on id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoProxyServiceImpl.java
> +					throw new IdRepoAppUncheckedException(FILE_NOT_FOUND);
we should throw in similar pattern. like above

throw new IdRepoAppUncheckedException(e.getErrorCode(), e.getErrorText(), e);

2023-09-28 06:20 UTC, vishwa-vyom approved these changes

2023-09-28 06:20 UTC, merged